### ISSUE TITLE
Errors building with patscc 0.3.9

### ISSUE THREAD

**Issue by doublec** [deech/LeftPad#1]
I tried building with patscc 0.3.9 built from the install script mentioned in the post. The ATS2 is at commit 28f0cde43. I got these build errors:

    left-pad.dats: 2117(line=90, offs=17) -- 2144(line=90, offs=44): error(3): the symbol [print] cannot be resolved as no match is found.
    left-pad.dats: 2117(line=90, offs=17) -- 2144(line=90, offs=44): error(3): the dynamic expression cannot be assigned the type [S2Ecst(atsvoid_t0ype)].
    left-pad.dats: 2117(line=90, offs=17) -- 2144(line=90, offs=44): error(3): mismatch of static terms (tyleq):
    The actual term is: S2Eerrexp()
    The needed term is: S2Ecst(atsvoid_t0ype)

This is on the line using `println!`. Any ideas what I'm missing?

**Comment by deech** [comment]
Here's the tip of my ATS source:
```
$ git log
commit 015b41486ba0ad681cc2590c53e9a9ad2f2dc26e
Author: Hongwei Xi <gmhwxi@gmail.com>
Date:   Sun Dec 3 21:49:44 2017 -0500

    Updating: very very minorly
```

I may have used the script that installs the [latest ATS](https://github.com/ats-lang/ats-lang.github.io/blob/master/SCRIPT/C9-ATS2-install-latest.sh).

**Comment by deech** [comment]
I think that was it. I moved to an older version and was able to replicate the error. I'll update the docs.

**Comment by deech** [comment]
Updated.

**Comment by doublec** [comment]
That fixed it, thanks!
